### ISSUE TITLE
Peer Review by David Qi

### ISSUE THREAD

**Issue by UTDQi** [LilianS77/US_Marriage#5]
1.	Summary
The paper uses logistic regression to analyze the factors that contribute to non-marriage of certain social and ethnic groups.

2.	Strong positive points:
The study uses appropriate variable selection and data selection for the issue. The IPUMS data base can be considered the most informed and relevant source concerning non-marriage of the US. 
Data are presented to the reader with clear visualization, along with concise and clear explanations. 
The model selection is well preformed and well explained. Explanation of model is clear and made it easy to for other to repeat what the author does. Justification made it reliable. 

3.	Critical improvements needed:
There are certain important model aspects that are not considered, such as not including the p value for each coefficient. And we may need the model diagnostic in appendixes. Appendix A.2 is too brief and does not justify model assumptions. 
There is not an appendix discussing where you focus on some aspect of this IPUMS data. What is the idealized methodology of collecting similar data? 

4.	Suggestions for improvement:
Sketch is not updated
I think taking 5000 randoms rows to analysis is not well justified, comparing to taking all rows. Or 80% as a training and 20% as validation. Please check. 
Delete unused scripts usch as scripts/07-replications.R. And unused csv analysis data.
The file name of the model folder is models/bayesian_model.rds, check if it is updated correctly. 
Certain graph labels uses label like "not_married" with the underscore, you may want space instead. 

5.	Evaluation:
R/Python cited (1/1 pts)
R is cited.

Data cited (1/1 pts)
Data sourse is cited.

Class paper (1/1 pts)
There is no indication of being a class paper.

LLM documentation (1/1 pts)
The entire chat history is available in the two files. 

Title (2/2 pts)
Title is informative, however I have the feeling it may be too long.  I will still give 2 since that is purely subjective feeling. 

Author, date, and repo (2/2 pts)
These are included in the paper.

Abstract (3/4 pts)
The abstract explains method and findings well. The author may want also to mention what data was used. 

Introduction (3/4 pts)
The introduction provide a good explaination of what will be done and why they was done. 

Estimand (1/1 pts)
Estimand is included.

Data (8/10 pts)
The data sources and variable visualization are explained with clear figures. The author may want to improve the labels. And have a more in depth explaination of each variable. 

Measurement (3/4 pts)
The Measurement section is is clear.

Model (6/10 pts)
Clear model explaination, may lack model diagonstics. 

Results (8/10 pts)
Detailed result section, however may lack p value as stated previously. 

Discussion (10/10 pts)
The discussion is sophisticated and informative. 

Prose (6/6 pts)
The article well written. 

Cross-references (1/1 pts)
Cross-references are used everywhere, with few missing(see page 6 of the paper) which is understandable at this stage

Captions (2/2 pts)
Clear figure captions

Graphs/tables/etc (3/4 pts)
The graphs are clear, with possible issue on label. 

Surveys, sampling, and observational data appendix (0/10 pts)
None

Referencing (4/4 pts)
The relevant references are included.

Commits (2/2 pts)
There are consistant commit messages.

Sketches (0/2 pts)
Not updated

Simulation (4/4 pts)
Relevant Simulation are conducted. 

Tests (4/4 pts)
Relevant test are conducted. 

Parquet (1/1 pts)
Parquet used, remember to delete csv file. 

Reproducible workflow (4/4 pts)
Workflow is reproducible.

Enhancements (0/4 pts)
I cannot find any part related "Enhancements". However there may exist certain aspects that are contacted through email and I do not know.

Miscellaneous (0/3 pts)
The author have not done much outside the rubric.

Estimated overall mark:
71 out of 112.

Any other comments:
No

**Comment by LilianS77** [comment]
Thanks for the advice! I tried my best to fixed issues.
